import '../models/place.dart';
import '../models/review.dart';

/// 初回起動時（ローカル保存が空のとき）に投入するサンプルデータ。
/// デザインカンプ（保存した場所 / 地図 / 口コミ詳細）に登場する
/// スポット・口コミをそのまま再現しています。
class SeedData {
  SeedData._();

  static List<Place> places() => [
        Place(
          id: 'p1',
          name: '一楽ラーメン',
          category: 'グルメ',
          quote: '濃厚なスープが絶品。福岡に来たら絶対に行くべき。30分待ちは覚悟して。',
          rating: 4.8,
          ratingCount: 1245,
          locationLabel: '福岡',
          footerLabel: '4.8',
          footerIconKey: 'star',
          photoIconKey: 'ramen',
          gradientColors: const [0xFF5A3320, 0xFFB5651D],
          isSaved: true,
          lat: 33.5902,
          lng: 130.4017,
        ),
        Place(
          id: 'p2',
          name: '東京タワー',
          category: '文化',
          quote: '定番のランドマーク。登るよりも遠くから（六本木ヒルズなど）見るのがおすすめ。',
          rating: 4.6,
          ratingCount: 982,
          locationLabel: '東京',
          footerLabel: '展望台',
          footerIconKey: 'visibility',
          photoIconKey: 'city',
          gradientColors: const [0xFF0D1B4C, 0xFF3A4A9A],
          isSaved: true,
          lat: 35.6586,
          lng: 139.7454,
        ),
        Place(
          id: 'p3',
          name: '草津温泉',
          category: '温泉',
          quote: '酸性が強く、肌に良い。夜の湯畑はとても幻想的。',
          rating: 4.7,
          ratingCount: 640,
          locationLabel: '群馬',
          footerLabel: 'リラクゼーション',
          footerIconKey: 'spa',
          photoIconKey: 'onsen',
          gradientColors: const [0xFF2F5233, 0xFF6B9362],
          isSaved: true,
          lat: 36.6199,
          lng: 138.5958,
        ),
        Place(
          id: 'p4',
          name: 'Koffee Mameya',
          category: 'グルメ',
          quote: '究極のコーヒー体験。ミニマルな空間と、熟練のバリスタ。',
          rating: 4.9,
          ratingCount: 410,
          locationLabel: '表参道',
          footerLabel: 'カフェ',
          footerIconKey: 'cafe',
          photoIconKey: 'coffee',
          gradientColors: const [0xFFC9A97E, 0xFFEFE3D0],
          isSaved: true,
          lat: 35.6690,
          lng: 139.7100,
        ),
        Place(
          id: 'p5',
          name: '新宿駅 東口',
          category: '交通',
          quote: '人が多すぎて、正直ムリ。ラッシュ時は絶対避けるべき。',
          rating: 2.1,
          ratingCount: 88,
          locationLabel: '東京',
          footerLabel: '交通',
          footerIconKey: 'transit',
          photoIconKey: 'train',
          gradientColors: const [0xFF555555, 0xFF8A8A8A],
          isSaved: false,
          lat: 35.6896,
          lng: 139.7006,
        ),
      ];

  static List<Review> reviews() => [
        Review(
          id: 'r1',
          placeId: 'p1',
          userName: 'サラ・J.',
          userTag: 'US',
          avatarColor: 0xFFE8A87C,
          stars: 5,
          comment:
              '信じられないほど素晴らしい体験でした。スープは濃厚で風味豊かで、豚肉は口の中でとろけました。並ぶ覚悟は必要ですが、価値は十分にあります。また福岡に来たら絶対にもう一度訪れたいお店です。',
          timeAgo: '2日前',
          helpfulCount: 24,
          photoCount: 3,
          isMine: false,
          createdAt: DateTime.now().subtract(const Duration(days: 2)),
        ),
        Review(
          id: 'r2',
          placeId: 'p1',
          userName: 'ケンジ・T.',
          userTag: 'JP',
          avatarColor: 0xFF9FB4C7,
          stars: 2,
          comment: 'スープは良かったですが、席が狭くて落ち着きませんでした。価格も少し高めに感じました。',
          timeAgo: '1週間前',
          helpfulCount: 5,
          photoCount: 0,
          isMine: false,
          createdAt: DateTime.now().subtract(const Duration(days: 7)),
        ),
        Review(
          id: 'r3',
          placeId: 'p5',
          userName: 'ユウキ・M.',
          userTag: 'JP',
          avatarColor: 0xFFB0B0B0,
          stars: 1,
          comment: '朝夕のラッシュ時は本当に人が多すぎる。ベビーカーや大きな荷物があると特に大変。',
          timeAgo: '3日前',
          helpfulCount: 12,
          photoCount: 1,
          isMine: false,
          createdAt: DateTime.now().subtract(const Duration(days: 3)),
        ),
        Review(
          id: 'r4',
          placeId: 'p2',
          userName: 'ミカ・S.',
          userTag: 'JP',
          avatarColor: 0xFFD8A0D8,
          stars: 5,
          comment: '夜のライトアップが本当に綺麗。六本木ヒルズの展望台から見る夜景は最高でした。',
          timeAgo: '5日前',
          helpfulCount: 18,
          photoCount: 2,
          isMine: false,
          createdAt: DateTime.now().subtract(const Duration(days: 5)),
        ),
        Review(
          id: 'r5',
          placeId: 'p3',
          userName: 'アンドリュー・K.',
          userTag: 'US',
          avatarColor: 0xFF8FBF9F,
          stars: 4,
          comment: '温泉のお湯が本当に気持ちよかった。ただ、朝は少し混雑していました。',
          timeAgo: '2週間前',
          helpfulCount: 9,
          photoCount: 1,
          isMine: false,
          createdAt: DateTime.now().subtract(const Duration(days: 14)),
        ),
        Review(
          id: 'r6',
          placeId: 'p4',
          userName: 'ゆい・N.',
          userTag: 'JP',
          avatarColor: 0xFFE0C097,
          stars: 5,
          comment: 'コーヒー一杯一杯へのこだわりがすごい。並ぶ価値あり、また来ます。',
          timeAgo: '4日前',
          helpfulCount: 15,
          photoCount: 2,
          isMine: false,
          createdAt: DateTime.now().subtract(const Duration(days: 4)),
        ),
      ];
}
