// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6hNnoq0uJkNVcR8hhGaSMIj5aRtsEyOc',
    appId: '1:584548655709:android:c23b43d8ce4289287b23b4',
    messagingSenderId: '584548655709',
    projectId: 'qooo-f4816',
    storageBucket: 'qooo-f4816.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_UGb80BDp-VclfgTaPzzfEiqVdeRNdJM',
    appId: '1:584548655709:ios:bcd75cf5cf1d713a7b23b4',
    messagingSenderId: '584548655709',
    projectId: 'qooo-f4816',
    storageBucket: 'qooo-f4816.firebasestorage.app',
    iosBundleId: 'com.example.qoo',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHc3vfLVU9EssJAOivbB5O8HIohy_zuVU',
    appId: '1:584548655709:web:1f5f94a3385ddcf97b23b4',
    messagingSenderId: '584548655709',
    projectId: 'qooo-f4816',
    authDomain: 'qooo-f4816.firebaseapp.com',
    storageBucket: 'qooo-f4816.firebasestorage.app',
    measurementId: 'G-WGKDK7H5P3',
  );
}
